### ISSUE TITLE
Synology DSM 7.1-42661 lässt den Zugriff aus einer VM auf das Modul per USB nicht mehr zu

### ISSUE THREAD

**Issue by Schlumpel** [alexreinert/PCB#11]
Habe den HB-RF-USB-TK an einer Raspberrymatic-OVA als Virtuelle Maschine sauber betreiben können. Seit DSM 7.1-42661 weigert sich die Raspberrymatic mit angestecktem Modul zu starten, bei einem Start der VM mit abgezogenem Modul klappt der Start, beim nachträglichen Einstecken und Aktivieren des Moduls passiert aber nichts mehr...
Bin ratlos. Der Synology Support ist angeschrieben, lässt aber noch auf sich warten.

Danke für Unterstützung

**Comment by alexreinert** [comment]
Sorry, ich kann weder für Synology, noch für RaspberryMatic, noch für die kommerzielle Version der Platine Support leisten.
Im Zweifel im RaspberryMatic Github ein Issue aufmachen oder im Homematic Forum nachfragen, ob jemand eine Idee hat.
