### ISSUE TITLE
Stromverbrauch HB-RF-USB-2

### ISSUE THREAD

**Issue by T1mey** [alexreinert/PCB#13]
Hallo, gibt es Infos wie hoch der zusätzliche Stromverbrauch der Platine ist?

**Comment by alexreinert** [comment]
je nach aufgestecktem Funkmodul zwischen 10 und 15mA.

**Comment by T1mey** [comment]
Liegen da 5V an ?

Eigentlich simple Frage ..  lohnt es sich ein pi3 abzuschalten und auf einen futro s740 mit HB-RF-USB-2 umzuziehen (den futro setze ich gerade auf) und will nicht unbedingt 2 systeme laufen lassen ...

**Comment by alexreinert** [comment]
Die Platine hat die vollständige Beschaltung um ein HM-MOD-RPI-PCB oder ein RPI-RF-MOD per USB anzuschließen und mit debmatic oder piVCCU auf den jeweils unterstützten Platformen zu betreiben. Beim RPI--RF-MOD darf kein externenes Netzteil genutzt werden.
Siehe einfach auch die Vorstellung der Platine im Homematic Forum.

Ob es sich lohnt, muss man selbst entscheiden, auf jeden Fall braucht die Platine deutlich weniger Strom als ein Pi.
