### ISSUE TITLE
HB-UNI-SEN-BATT

### ISSUE THREAD

**Issue by Hasenpups** [alexreinert/PCB#2]
Hallo, 

Leider sind 3 Leiterbahnen vom CC1101 mit der Massefläche auf der Rückseite der Platine verbunden. Dadurch kann der CC1101 nicht richtig vom Arduino angesprochen werden. 
![hb-uni-sen-batt](https://user-images.githubusercontent.com/29422053/43413801-528a28c8-9431-11e8-9e44-12fc2261bc3d.jpeg)

Ich denke der Fehler ist passiert als du unten die Pins für das flashen des Bootloaders hinzugefügt hast.

**Comment by alexreinert** [comment]
Hhm, ich habe die Platinen hier liegen und da ist das nicht der Fall. Auch die Lötstoppfreistellung zwischen den Pins vom Arduino sieht sehr befremdlich aus und das habe ich so noch nie gesehen. Ich fürchte fast, dass da mit git irgendwas falsch zusammengemerged wurde. Schau ich mir mal an, sobalb ich wieder an meinem Rechner bin.

**Comment by Hasenpups** [comment]
Hab die Dateien mal bei dirtypcb und jlcpcb rendern lassen. Sieht bei beiden identisch aus. 
![img_4005](https://user-images.githubusercontent.com/29422053/43414492-30944f58-9433-11e8-975c-17af9083b38f.JPG)
Ich hab die Bahnen jetzt mal mit einem Cuttermesser getrennt und jetzt kann auch der CC1101 und der BME280 korrekt angesprochen werden.
