### ISSUE TITLE
Info bzgl. weitere Platinen

### ISSUE THREAD

**Issue by LeelooDallas-github** [alexreinert/PCB#4]
Wow, schöne Sachen die Du hier gebaut hast.
Ggf. ist in dieser Ecke auch was für Dich dabei.
https://forum.fhem.de/index.php/topic,73954.0.html

CU Leeloo

**Comment by alexreinert** [comment]
Danke für die Info, die sind mir bereits bekannt. Das hier ist einfach die Sammlung meiner Platinen und erhebt nicht den Anspruch einer Übersicht aller für HM verfügbaren Platinen, wie sie z.B. auf asksinpp.de gepflegt wird.
