### ISSUE TITLE
HB-RF-USB-2 question

### ISSUE THREAD

**Issue by KrX3D** [alexreinert/PCB#5]
hello,

i have got an HM-MOD-RPI-PCB , can i also use it on my nas where i have unraid running and iobroker in docker? or can it only be run with raspberry?

**Comment by alexreinert** [comment]
This is just a pcb. If piVCCU or debmatic and the matching kernel are running on your nas, depends on your nas, but you gave no information about it.

**Comment by KrX3D** [comment]
hi, my nas (hardware) is self made. and it is running unraid:

https://unraid.net/

if im not mistaken its linux based.
on it im running several docker images like iobroker etc.

do you know it it is possible to run piVCCU or debmatic with an docker image or virtual machine?

thanks in advance

**Comment by alexreinert** [comment]
Docker is not supported, as there is the need to load and access special kernel modules, which is not possible inside a docker container.
(Real) VMs like kvm are supported. piVCCU does only support ARM/ARM64 hardware, debmatic support both x64 and ARM.

**Comment by KrX3D** [comment]
ok thanks for the info, if i get it running somehow i will post it here, so others can profit from it.
