### ISSUE TITLE
Clarification: Ferrite Bead

### ISSUE THREAD

**Issue by dersimn** [alexreinert/PCB#6]
> - 1x Ferrite Bead 100Ohm, 800mA 0805 (L1)

Really 100 Ω? Not 100 *m*Ω?
Can you recommend a specific part? Maybe from Reichelt, Aliexpress, Farnell?

**Comment by alexreinert** [comment]
100 Ohm is correct. This is not the DC resistance, it is the resistence for high frequencies. A possible part would be https://m.de.aliexpress.com/item/4000444822616.html?pid=808_0003_0101&spm=a2g0n.search-amp.list.4000444822616&aff_trace_key=&aff_platform=msite&m_page_id=2046amp-izJHbqX1ctc-Y0-KukobSg1595613636311&browser_id=24b0c7544e3b4890a36249c19dac0a26&is_c=Y

**Comment by dersimn** [comment]
Ah, yeah makes sense. Thank you!
