### ISSUE TITLE
Reset vs. ^Reset

### ISSUE THREAD

**Issue by dersimn** [alexreinert/PCB#7]
Wieso erhalten beide Aufsteckboards (HM-MOD-RPI-PCB und RPI-RF-MOD) bei der **HB-RF-USB** das selbe Signal (jeweils Pin 12, 35) während das Signal bei der **HB-RF-USB-2** invertiert wird?

## HB-RF-USB
![Screenshot 2020-08-28 at 11 17 56](https://user-images.githubusercontent.com/3258452/91544555-2cea4f80-e920-11ea-943d-5d63702922ea.png)

## HB-RF-USB-2
![Screenshot 2020-08-28 at 11 18 29](https://user-images.githubusercontent.com/3258452/91544603-3d9ac580-e920-11ea-82d9-26bb4cb6b35c.png)

**Comment by alexreinert** [comment]
Das RPI-RF-MOD invertiert das Reset Signal. Das ist mir bei der HB-RF-USB aber erst aufgefallen, nachdem ich den ersten Hardware Prototypen hatte. Der FT232RL bei der HB-RF-USB kann aber im Zustand Floating bleiben, in welchem sowohl das RPI-RF-MOD, als auch das HM-MOD-RPI-PCB die Reset Leitung selbständig in den richtigen Zustand ziehen um nicht im Reset zu sein. Zum Reseten kann man aber einfach einmal kurz auf High und auf Low gehen und danach wieder auf Floating und damit können beide Module zuverlässig resettet werden.
Der CP2102N vom HB-RF-USB-2 kann nicht in den Zustand Floating gebracht werden, daher muss für eines der beiden Module eine Invertierung vorgenommen werden und doppelte Invertierung für das RPI-RF-MOD fand ich doof, so dass jetzt beide Module einmal invertiert werden.
